FROM openjdk:latest
MAINTAINER martyna.drabinska@gmail.com
ADD /target/catering-app-0.0.1-SNAPSHOT.jar /opt/spring-cloud/lib/
CMD java -jar /opt/spring-cloud/lib/catering-app-0.0.1-SNAPSHOT.jar
EXPOSE 8080